# Initial zookeeper vagrant file
# TODO use a better provisioning for handling conf files
Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.chaos_monkey.burn_cpus = 1
  config.vm.define ("zookeeper_node") do |machine|
    machine.vm.network :public_network, :ip => "192.168.1.99"
    # change that to use chef/puppet
    machine.vm.provision "shell", path: "install_zookeeper.sh"
  end
end
