# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "precise64"
  config.vm.network :public_network
  # change that to use chef/puppet
  config.vm.provision "shell", path: "install_memcached.sh"
end
