# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'json'

Vagrant.configure(2) do |config|
  # If the file doesn't exist, make ips automatics
  ips = File.exist?("ips.json") ? JSON.parse(open("ips.json").readline()) : nil
  n = ips.nil? ? 1 : ips.length
  config.vm.box = "precise64"
  (1..n).each do |i|
    config.vm.define ("loadbalancer_node%d" % i) do |machine|
      options = {}
      unless ips.nil?
        options[:ip] =  ips[i-1]
      end
      machine.vm.network :public_network , options
      # change that to use chef/puppet
      machine.vm.provision "shell", path: "install_apache2.sh"
    end
  end
  config.vm.define("loadbalancer") do |machine|
    machine.vm.network :public_network
    machine.vm.provision "haproxy_provisioner" do |p|
      p.ips = ips.nil? ? [] : ips
    end

  end
end
